server.port : 8080
spring:
  cloud:
    gateway:
      routes:
        - id: product-svc
          uri: lb://PRODUCT-SVC
          predicates:
            - Path= /product/**
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/