svc.inventory.url: "http://localhost:8082"
svc.catalog.url: "http://localhost:8083/Product"
server.port : 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/